spring:
  main:
    web-application-type: reactive
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://34.125.109.178:3306/okestro
    username: root
    password: user1234
  level:
    root: info
  batch:
    jdbc:
      initialize-schema: always

server:
  port: 8081


